apiVersion: v1
kind: Service
metadata:
  namespace: learn-namespace
  name: aks-demo-service
spec:
  selector:
    app: aks-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
