name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - uses: actions/checkout@v4

      # Step 2: Log in to Cloudsmith Docker registry
      - name: Log in to Cloudsmith
        run: echo "${{ secrets.CLOUDSMITH_API_KEY }}" | docker login docker.cloudsmith.io -u ${{ secrets.CLOUDSMITH_USERNAME }} --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          IMAGE_TAG=aks-demo-img:latest
          docker build -t docker.cloudsmith.io/lp-pc00/learning-demo-cldsmith/$IMAGE_TAG .

      # Step 4: Push the Docker image to Cloudsmith
      - name: Push Docker image
        run: |
          docker push docker.cloudsmith.io/lp-pc00/learning-demo-cldsmith/aks-demo-img:latest
          
      # Step 5: Azure login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 6: Get AKS credentials
      - name: Setup AKS
        run: |
              az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      # Step 7: Deploy to AKS
      - name: Deploy to AKS
        run: |
              kubectl apply -f k8/deployment.yaml
              kubectl apply -f k8/service.yaml
             
